### PR TITLE
Grid layout

### PR DESCRIPTION
**Pull request by pdewouters**
Exploring drag and drop interface

### CODE REVIEW

**Comment by roborourke** [comment]
What's the status of this? Does it work?

**Comment by pdewouters** [comment]
@roborourke I can demo if you want.

**Comment by pdewouters** [comment]
@roborourke can we close this?

**Comment by roborourke** [comment]
Yeah we can archive this repo
-- 
Robert O'Rourke
Product Engineer
Human Made Limited <https://humanmade.com/>

<https://humanmade.com/enterprise-wordpress-newsletter/?utm_source=email&utm_campaign=email_ro>

*Get the inside track on enterprise WordPress news in your inbox once a
month
<https://humanmade.com/enterprise-wordpress-newsletter/?utm_source=email&utm_campaign=email_ro>.
Make more informed decisions starting today.*

**Pull request closed without merging**
